// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hopefullythiswillbeaddingthejunctiontable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hopefullythiswillbeaddingthejunctiontable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261514197_hopefully this will be adding the junction table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
