namespace pwlc.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class workingonautogeneratedidforpatients : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Checkups", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Events", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Injections", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Invoices", "Patient_PatientId", "dbo.Patients");
            DropPrimaryKey("dbo.Patients");
            AlterColumn("dbo.Patients", "PatientId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.Patients", "PatientId");
            AddForeignKey("dbo.Checkups", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Events", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Injections", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Invoices", "Patient_PatientId", "dbo.Patients", "PatientId");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Invoices", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Injections", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Events", "Patient_PatientId", "dbo.Patients");
            DropForeignKey("dbo.Checkups", "Patient_PatientId", "dbo.Patients");
            DropPrimaryKey("dbo.Patients");
            AlterColumn("dbo.Patients", "PatientId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.Patients", "PatientId");
            AddForeignKey("dbo.Invoices", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Injections", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Events", "Patient_PatientId", "dbo.Patients", "PatientId");
            AddForeignKey("dbo.Checkups", "Patient_PatientId", "dbo.Patients", "PatientId");
        }
    }
}
