// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newmigrationafterremovingdatabaseandmigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmigrationafterremovingdatabaseandmigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201705222100081_new migration after removing database and migrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
