// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class workingonautogeneratedidforpatients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workingonautogeneratedidforpatients));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221504355_working on auto generated id for patients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
