// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editedcheckuptoincludeoptionfornullables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedcheckuptoincludeoptionfornullables));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221714323_edited checkup to include option for nullables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
