// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class workingonlookuptableandforeignkeyforappointmentTypeandEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workingonlookuptableandforeignkeyforappointmentTypeandEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231639477_working on lookup table and foreignkey for appointmentType and Event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
