// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedlistofitemstoinvoiceandlistofinvoicestopatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedlistofitemstoinvoiceandlistofinvoicestopatient));
        
        string IMigrationMetadata.Id
        {
            get { return "201705241933418_added list of items to invoice and list of invoices to patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
