// <auto-generated />
namespace pwlc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingdurationfrominttodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingdurationfrominttodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201705232055339_changing duration from int to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
