// <auto-generated />
namespace PwlcApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edittopatientmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edittopatientmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181935327_edit to patient model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
